title: Yongjie
description: As free as the wind.
author: Yongjie Zhou
avatar: /logo.png
email: sixpencezyj@yeah.net
location: Beijing China


plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: ngzhio
  card: summary
logo: logo.png
social:
  name: Yongjie Zhou
  links:
    - https://twitter.com/ngzhio
    - https://www.facebook.com/ngzhio
    - https://github.com/zhouyongjie
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
